In [1]:
import numpy as np
def PowerMethod_Scaling(A, x, k):
    # Theorem 4.28 (p.312)
    y=x
    for i in range(k):
        x = A @ y
        m=x[abs(x).argmax(axis=0)].item(0)
        y=(1/m)*x
        print('i = {}'.format(i+1))
        print('x = \n {}'.format(x))
        print('m = {}'.format(m))

A=np.mat([[0,5,-6],
          [-4,12,-12],
          [-2,-2,10]])
x=np.mat([[1],
       [1],
       [1]])
k=8

PowerMethod_Scaling(A, x, k)

i = 1
x = 
 [[-1]
 [-4]
 [ 6]]
m = 6
i = 2
x = 
 [[ -9.33333333]
 [-19.33333333]
 [ 11.66666667]]
m = -19.333333333333332
i = 3
x = 
 [[ 8.62068966]
 [17.31034483]
 [-9.        ]]
m = 17.310344827586206
i = 4
x = 
 [[ 8.11952191]
 [16.24701195]
 [-8.19521912]]
m = 16.247011952191237
i = 5
x = 
 [[ 8.02648357]
 [16.05394801]
 [-8.04364885]]
m = 16.05394801373222
i = 6
x = 
 [[ 8.00623205]
 [16.0125863 ]
 [-8.01032566]]
m = 16.012586301704648
i = 7
x = 
 [[ 8.001511  ]
 [16.00303726]
 [-8.0025107 ]]
m = 16.003037263715377
i = 8
x = 
 [[ 8.00037196]
 [16.00074582]
 [-8.00061897]]
m = 16.000745819547912


### Use the Rayleigh quotient method to approximate the dominant eigenvalue and eigenvector of A

In [1]:
import numpy as np

def IP(x,y):
    xx=x.T
    xy=np.dot(xx,y)
    return xy.item(0)


def PowerMethod_Scaling(A, x, k,e):
    y=x
    r=100
    for i in range(k):
        x = A @ y
        r_i=IP(A@x,x)/IP(x,x)
        print('i = {}'.format(i+1))
        print('R(x) = {}'.format(r_i))
        if abs(r_i-r)<=e:
            break
        y=x
        r=r_i

A=np.array([[3,1,0],
          [1,3,1],
          [0,1,3]])
x=np.array([[1],
           [1],
           [1]])
k=6
e=10
PowerMethod_Scaling(A, x, k,e)

i = 1
R(x) = 4.4035087719298245
i = 2
R(x) = 4.412827461607949
